version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      DB_NAME: "taskdb"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - backend_network

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskdb
    volumes:
      - db_data:/data/db
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
    driver: bridge